### ISSUE TITLE
Mandatory set fixed-length terms for moderators

### ISSUE THREAD

**Issue by hook-s3c** [MilkManzJourDaddy/matrix-org#31]
Proposal to set fixed-length terms for moderators to avoid abuse of power; moderators rising above their station in what should reflect a decentralized community model.

I heard you had a bit of trouble today.

**Comment by MilkManzJourDaddy** [comment]
You should discuss this with your therapist and find venues more fitting for your angst.  If you cannot follow the rules of a venue, relocate to another venue such as off-topic rooms in online chats.

Anyway this is inappropriate for this repository and only a futile attempt at cyberstalking.

**Comment by MilkManzJourDaddy** [comment]
Matrix is not Decentralized-P2P (Peer to Peer / Ad Hoc), but Decentralized-Federated with Homeserver infrastructure.  

Those preferring total disruption and destruction of all structure may prefer something like GNU Ring which is promising.  However, the DHT may not protect I.P. Address privacy from peers in metadata, whereas with Matrix I.P. Address information is trusted to Homeserver Dev'Op's, et alia.

Anyway, counterproductive cyberstalkers will be blocked.  Simple.  Done.
